import React from 'react';

//The cards are getting the propertie (props) from robot.js
//Function that returns a card with one unique image. Th image is generated by the ID.
const Card = ({email, name, id}) => { //With destructuring we don't have to use props, just the name of the atribute
  return(
    <div className="tc bg-light-green dib br3 pa3 ma2 grow bw2 shadow-5">
      <img src={`https://robohash.org/${id}?200x200`} alt='One roboto'/>
      <div>
        <h2>{name}</h2>
        <p>{email}</p>
      </div>
    </div>
  );
}

export default Card;